name: ExamplePlugin
version: '${project.version}'
main: me.refracdevelopment.example.ExamplePlugin
authors:
  - Refrac
api-version: "1.13"
softdepend:
  - NBTAPI
  - PlaceholderAPI
  - Skulls
  - HeadDatabase
description: An Example plugin
website: https://discord.gg/EFeSKPg739
folia-supported: true