name: ExamplePlugin
version: '@version@'
main: me.refracdevelopment.example.ExamplePlugin
author: RefracDevelopment
api-version: "1.13"
depend:
  - PlaceholderAPI
description: An Example plugin
website: https://discord.refracdev.ml/